[package]
name = "interactsh-rs"
version = "0.1.0-RC1"
edition = "2021"
authors = ["Matt George <pyroraptor07@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A Rust client library for working with Interact.sh servers"
readme = "README.md"
repository = "https://github.com/pyroraptor07/interactsh-rs"
keywords = ["interactsh", "oob-interactions"]


[features]
default = ["rustcrypto", "reqwest-rustls-tls", "async-compat"]

# Crypto features
openssl = ["dep:openssl"]
openssl-vendored = ["openssl", "openssl?/vendored"]
rustcrypto = ["dep:rsa", "dep:aes", "dep:cfb-mode", "dep:sha2", "dep:digest", "dep:inout"]

# Reqwest features
reqwest-native-tls = ["reqwest/default-tls"]
reqwest-native-tls-vendored = ["reqwest-native-tls", "reqwest/native-tls-vendored"]
reqwest-rustls-tls = ["reqwest/rustls-tls"]
# reqwest-socks-proxy = ["reqwest/socks"]

# Other features
async-compat = ["dep:async-compat"]
# trace = ["dep:tracing"]
nightly = []


[dependencies]
base64 = "0.13"
cfg-if = "1"
rand = "0.8.5"
reqwest = { version = "0.11", default-features = false, features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
svix-ksuid = "0.6"
secrecy = "0.8"
thiserror = "1.0.36"
time = { version = "0.3.14", features = ["serde", "formatting", "parsing"] }
uuid = { version = "1", features = ["v4"] }

# RustCrypto dependencies
aes = { version = "0.8.1", optional = true }
cfb-mode = { version = "0.8.2", optional = true }
digest = { version = "0.10.5", optional = true }
inout = { version = "0.1.3", features = ["std"], optional = true }
rsa = { version = "0.6.1", optional = true }
sha2 = { version = "0.10.6", optional = true }

# Native crypto dependencies
openssl = { version = "0.10.41", optional = true }

# Other optional dependencies
async-compat = { version = "0.2", optional = true }
# tracing = { version = "0.1", optional = true }

[dev-dependencies]
async-compat = "0.2"
tokio = { version = "1", default-features = false, features = ["macros", "rt"] }
async-std = { version = "1", features = ["attributes"] }
smol = "1"
hex = "0.4"
fake = "2.5"
trust-dns-resolver = "0.22"
dotenvy = "0.15"
once_cell = "1.15"

[build-dependencies]
rustversion = "1"
